version: '3'
services:
  # redis:
  #   container_name: redis
  #   image: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ../data/redis:/data
  #   restart: always
  # rabbitmq:
  #   image: "rabbitmq:3-management"
  #   hostname: "rabbit"
  #   ports:
  #     - "15672:15672"
  #     - "5672:5672"
  #   labels:
  #     NAME: "rabbitmq"
  #   volumes:
  #     - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
  #   environment:
  #     - RABBITMQ_USERNAME = "username"
  #     - RABBITMQ_PASSWORD = "password"
  mongorestore --drop --host=localhost --port=27011 --username="ws" --password="ws!" --authenticationDatabase=admin -d social_network
  mongo:
    image: mongo:3.4
    container_name: mongo
    ports:
      - 27011:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'ws'
      MONGO_INITDB_ROOT_PASSWORD: 'ws!'
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'